channels:
  - conda-forge
dependencies:
  - r-base=4.2
  - r-tidyverse
  - r-writexl
  - r-markdown
  - r-rmarkdown
  - r-tinytex
  - r-pacman
  - r-magrittr
  - r-aod
  - r-ggplot2
  - r-caTools
  - r-rpart
  - r-rpart.plot
  - r-randomForest
  - r-party
  - r-tree
  - r-magrittr
  - r-visreg
  - r-rattle
  - r-remotes
